services:
  - type: web
    name: django-backend
    env: python
    workingDir: server
    buildCommand: ls -R
    startCommand: gunicorn newproject.newproject.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"