# Generated by Django 5.2.6 on 2025-09-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('expiration_date', models.DateField()),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_in_pantry', models.BooleanField(default=False)),
            ],
        ),
    ]
